### ISSUE TITLE
memory cost

### ISSUE THREAD

**Issue by whalien-902** [ripl/nerfuser#3]
What is the memory consumption of the model and what environment it needs to function properly. I tried running the code on 3090ti but it shows insufficient memory

**Comment by whalien-902** [comment]
and I miss some errors
![617488567021cc3e089c4b42be417b8](https://github.com/ripl/nerfuser/assets/102122699/2fc7fda9-8ad8-4e26-93be-407d6a280fc1)

**Comment by shengjie-lin** [comment]
For training your own nerf models, 6G is enough according to [Nerfacto](https://docs.nerf.studio/en/latest/nerfology/methods/nerfacto.html). For registration and blending, it should require even less than that.
As to the error you got, it is probably due to the fact that Nerfacto gets updated in its architectural design, and you are using our provided nerf model weights that are trained from an eariler version of Nerfacto. You can always train nerfs yourself by following our instructions.

**Comment by whalien-902** [comment]
Thank you, reply this.
